blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/aryan-dani/Portfolio/discussions/new?category=q-a
    about: Ask the community for help
  - name: Request a feature
    url: https://github.com/aryan-dani/Portfolio/issues/new?template=feature_request.yml
    about: Share ideas for new features
  - name: Report a bug
    url: https://github.com/aryan-dani/Portfolio/issues/new?template=bug_report.yml
    about: Report a reproducible bug
